version: "3"
services: 
  node-app:
    build: .
    # for now the port is the same but port for development and production environment can be different
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000