version: "3"
services: 
  node-app:
    build: 
      # context will contain the path to the Dockerfile
      context: .
      # args will contain variables to send to the Dockerfile when building the image
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
    # override the command from Dockerfile
    command: npm run dev