version: "3"
services:
  node-app:
    # build receives the path to the Dockerfile
    build: .
    # ports receives a list of port and they are seperated by \n and -, the - signifies a list
    ports: 
      - "3000:3000"
      # - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment: 
      - PORT=3000
    # env_file: 
    #   - ./.env